using System;
using System.Collections.Generic;
using System.Reflection;

namespace ILRuntime.Runtime.Generated
{
    class CLRBindings
    {

        internal static ILRuntime.Runtime.Enviorment.ValueTypeBinder<UnityEngine.Vector2> s_UnityEngine_Vector2_Binding_Binder = null;
        internal static ILRuntime.Runtime.Enviorment.ValueTypeBinder<UnityEngine.Vector3> s_UnityEngine_Vector3_Binding_Binder = null;
        internal static ILRuntime.Runtime.Enviorment.ValueTypeBinder<UnityEngine.Vector4> s_UnityEngine_Vector4_Binding_Binder = null;
        internal static ILRuntime.Runtime.Enviorment.ValueTypeBinder<UnityEngine.Quaternion> s_UnityEngine_Quaternion_Binding_Binder = null;

        /// <summary>
        /// Initialize the CLR binding, please invoke this AFTER CLR Redirection registration
        /// </summary>
        public static void Initialize(ILRuntime.Runtime.Enviorment.AppDomain app)
        {
            System_Boolean_Binding.Register(app);
            System_String_Binding.Register(app);
            BDebug_Binding.Register(app);
            System_Collections_Generic_List_1_Type_Binding.Register(app);
            BDFramework_ILRuntimeHelper_Binding.Register(app);
            System_Reflection_Assembly_Binding.Register(app);
            System_Linq_Enumerable_Binding.Register(app);
            System_Collections_Generic_List_1_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_List_1_Type_Binding_Enumerator_Binding.Register(app);
            System_Object_Binding.Register(app);
            BDFramework_GameStart_GameStartAtrribute_Binding.Register(app);
            System_IDisposable_Binding.Register(app);
            System_Collections_Generic_List_1_ILTypeInstance_Binding_Enumerator_Binding.Register(app);
            BDFramework_GameStart_IGameStart_Binding.Register(app);
            BDFramework_BDLauncher_Binding.Register(app);
            System_Action_Binding.Register(app);
            IEnumeratorTool_Binding.Register(app);
            BDFramework_GameConfig_Binding.Register(app);
            System_Runtime_CompilerServices_AsyncVoidMethodBuilder_Binding.Register(app);
            LitJson_JsonMapper_Binding.Register(app);
            System_Action_1_String_Binding.Register(app);
            System_Action_2_Int32_Int32_Binding.Register(app);
            UnityEngine_UI_Button_Binding.Register(app);
            UnityEngine_Events_UnityEvent_Binding.Register(app);
            UnityEngine_Object_Binding.Register(app);
            System_Collections_Generic_List_1_GameObject_Binding.Register(app);
            System_Collections_Generic_IEnumerable_1_KeyValuePair_2_String_Object_Binding.Register(app);
            System_Collections_Generic_IEnumerator_1_KeyValuePair_2_String_Object_Binding.Register(app);
            System_Collections_Generic_KeyValuePair_2_String_Object_Binding.Register(app);
            System_Collections_IEnumerator_Binding.Register(app);
            System_Collections_Generic_List_1_GameObject_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_List_1_Int32_Binding.Register(app);
            BDFramework_ResourceMgr_BResources_Binding.Register(app);
            System_Collections_Generic_List_1_String_Binding.Register(app);
            UnityEngine_Application_Binding.Register(app);
            BDFramework_VersionContrller_VersionContorller_Binding.Register(app);
            UnityEngine_Camera_Binding.Register(app);
            UnityEngine_Random_Binding.Register(app);
            System_Int32_Binding.Register(app);
            UnityEngine_UI_Text_Binding.Register(app);
            System_DateTime_Binding.Register(app);
            System_Array_Binding.Register(app);
            UnityEngine_WaitForSeconds_Binding.Register(app);
            System_NotSupportedException_Binding.Register(app);
            UnityEngine_Transform_Binding.Register(app);
            System_NotImplementedException_Binding.Register(app);
            System_Text_StringBuilder_Binding.Register(app);
            System_Collections_IEnumerable_Binding.Register(app);
            Google_Protobuf_ByteString_Binding.Register(app);
            ETModel_ByteHelper_Binding.Register(app);
            System_Exception_Binding.Register(app);
            System_Collections_IDictionary_Binding.Register(app);
            ETModel_Log_Binding.Register(app);
            ETModel_IdGenerater_Binding.Register(app);
            UnityEngine_GameObject_Binding.Register(app);
            ETModel_MongoHelper_Binding.Register(app);
            ETModel_LayerNames_Binding.Register(app);
            ETModel_ComponentView_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Type_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Type_ILTypeInstance_Binding_ValueCollection_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Type_ILTypeInstance_Binding_ValueCollection_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_HashSet_1_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_HashSet_1_ILTypeInstance_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_List_1_Object_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_String_List_1_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Int64_ILTypeInstance_Binding.Register(app);
            ETModel_UnOrderMultiMap_2_Type_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_Queue_1_Int64_Binding.Register(app);
            ETModel_Game_Binding.Register(app);
            ETModel_Hotfix_Binding.Register(app);
            ETModel_EventAttribute_Binding.Register(app);
            ETModel_EventProxy_Binding.Register(app);
            ETModel_EventSystem_Binding.Register(app);
            System_Collections_Generic_Queue_1_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Type_ILTypeInstance_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_KeyValuePair_2_Type_ILTypeInstance_Binding.Register(app);
            ETModel_Define_Binding.Register(app);
            ETModel_Entity_Binding.Register(app);
            ETModel_ResourcesComponent_Binding.Register(app);
            ETModel_ConfigAttribute_Binding.Register(app);
            ETModel_AppTypeHelper_Binding.Register(app);
            ETModel_GameObjectHelper_Binding.Register(app);
            UnityEngine_TextAsset_Binding.Register(app);
            ETModel_AsyncETTaskMethodBuilder_Binding.Register(app);
            ETModel_ETTask_Binding.Register(app);
            ETModel_ETTask_Binding_Awaiter_Binding.Register(app);
            ETModel_AsyncETVoidMethodBuilder_Binding.Register(app);
            ETModel_GlobalConfigComponent_Binding.Register(app);
            ETModel_GlobalProto_Binding.Register(app);
            ETModel_NetworkComponent_Binding.Register(app);
            ETModel_ETTask_1_IMessageAdapter_Binding_Adaptor_Binding.Register(app);
            ETModel_ETTask_1_IMessageAdapter_Binding_Adaptor_Binding_Awaiter_Binding.Register(app);
            ETModel_SessionComponent_Binding.Register(app);
            ETModel_ComponentFactory_Binding.Register(app);
            ETModel_PlayerComponent_Binding.Register(app);
            ETModel_SceneChangeComponent_Binding.Register(app);
            ETModel_C2G_EnterMap_Binding.Register(app);
            ETModel_Session_Binding.Register(app);
            ETModel_ETTask_1_IResponse_Binding.Register(app);
            ETModel_ETTask_1_IResponse_Binding_Awaiter_Binding.Register(app);
            ETModel_G2C_EnterMap_Binding.Register(app);
            ETModel_Player_Binding.Register(app);
            ETModel_M2C_CreateUnits_Binding.Register(app);
            Google_Protobuf_Collections_RepeatedField_1_UnitInfo_Binding.Register(app);
            System_Collections_Generic_IEnumerator_1_UnitInfo_Binding.Register(app);
            ETModel_UnitInfo_Binding.Register(app);
            ETModel_UnitComponent_Binding.Register(app);
            ETModel_UnitFactory_Binding.Register(app);
            UnityEngine_Vector3_Binding.Register(app);
            ETModel_Unit_Binding.Register(app);
            ETModel_M2C_PathfindingResult_Binding.Register(app);
            ETModel_AnimatorComponent_Binding.Register(app);
            ETModel_UnitPathComponent_Binding.Register(app);
            ETModel_ETVoid_Binding.Register(app);
            ETModel_GizmosDebug_Binding.Register(app);
            System_Collections_Generic_List_1_Vector3_Binding.Register(app);
            Google_Protobuf_Collections_RepeatedField_1_Single_Binding.Register(app);
            UnityEngine_LayerMask_Binding.Register(app);
            UnityEngine_Input_Binding.Register(app);
            UnityEngine_Physics_Binding.Register(app);
            UnityEngine_RaycastHit_Binding.Register(app);
            ETModel_Frame_ClickMap_Binding.Register(app);
            ReferenceCollector_Binding.Register(app);
            ETModel_ActionHelper_Binding.Register(app);
            ETModel_AssetBundleHelper_Binding.Register(app);
            UnityEngine_UI_InputField_Binding.Register(app);
            Google_Protobuf_ProtoPreconditions_Binding.Register(app);
            Google_Protobuf_CodedOutputStream_Binding.Register(app);
            Google_Protobuf_CodedInputStream_Binding.Register(app);
            Google_Protobuf_MessageParser_1_IMessageAdapter_Binding_Adaptor_Binding.Register(app);
            Google_Protobuf_Collections_RepeatedField_1_IMessageAdapter_Binding_Adaptor_Binding.Register(app);
            Google_Protobuf_Collections_RepeatedField_1_String_Binding.Register(app);
            Google_Protobuf_Collections_RepeatedField_1_Int32_Binding.Register(app);
            Google_Protobuf_Collections_RepeatedField_1_Int64_Binding.Register(app);
            Google_Protobuf_FieldCodec_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_UInt16_List_1_ILTypeInstance_Binding.Register(app);
            ETModel_OpcodeTypeComponent_Binding.Register(app);
            ETModel_MessageProxy_Binding.Register(app);
            ETModel_MessageDispatcherComponent_Binding.Register(app);
            ETModel_MessageInfo_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Type_Queue_1_Object_Binding.Register(app);
            System_Collections_Generic_Queue_1_Object_Binding.Register(app);
            ETModel_DoubleMap_2_UInt16_Type_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_UInt16_Object_Binding.Register(app);
            ETModel_MessageAttribute_Binding.Register(app);
            ETModel_SessionCallbackComponent_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Int32_Action_1_IMessageAdapter_Binding_Adaptor_Binding.Register(app);
            System_Action_1_IMessageAdapter_Binding_Adaptor_Binding.Register(app);
            ETModel_Component_Binding.Register(app);
            ETModel_IMessagePacker_Binding.Register(app);
            ETModel_OpcodeHelper_Binding.Register(app);
            ETModel_StringHelper_Binding.Register(app);
            ETModel_ETTaskCompletionSource_1_IMessageAdapter_Binding_Adaptor_Binding.Register(app);
            System_Threading_CancellationToken_Binding.Register(app);
            ETModel_ErrorCode_Binding.Register(app);
            ETModel_RpcException_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_String_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_String_ILTypeInstance_Binding_ValueCollection_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_String_ILTypeInstance_Binding_ValueCollection_Binding_Enumerator_Binding.Register(app);
            UnityEngine_Canvas_Binding.Register(app);
            SQLite4Unity3d_SQLiteConnection_Binding.Register(app);
            SQLite4Unity3d_SQLiteCommand_Binding.Register(app);
            System_Collections_Generic_List_1_Object_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_List_1_APITestHero_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_String_Object_Binding.Register(app);
            System_Net_WebClient_Binding.Register(app);
            System_Threading_Tasks_Task_1_String_Binding.Register(app);
            System_Runtime_CompilerServices_TaskAwaiter_1_String_Binding.Register(app);
            Code_BDFramework_UnitTest_Test_APITestHero_Binding.Register(app);
            BDFramework_Sql_SqliteLoder_Binding.Register(app);
            BDFramework_ResourceMgr_IResMgr_Binding.Register(app);
            UnityEngine_UI_ScrollRect_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_String_MemberInfo_Binding.Register(app);
            System_Collections_Generic_List_1_MemberInfo_Binding.Register(app);
            System_Collections_Generic_List_1_MemberInfo_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Type_Dictionary_2_String_MemberInfo_Binding.Register(app);
            Mono_Cecil_MemberReference_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_String_Type_Binding.Register(app);
            ILRuntime_Runtime_Enviorment_AppDomain_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_String_IType_Binding.Register(app);
            ILRuntime_CLR_TypeSystem_IType_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_String_Action_2_UIBehaviour_Object_Binding.Register(app);
            System_Action_2_UIBehaviour_Object_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_String_Action_2_Transform_Object_Binding.Register(app);
            System_Action_2_Transform_Object_Binding.Register(app);
            UnityEngine_Behaviour_Binding.Register(app);
            UnityEngine_Events_UnityEventBase_Binding.Register(app);
            BDFramework_UFlux_IButton_Binding.Register(app);
            BDFramework_UFlux_IComponentOnClick_Binding.Register(app);
            UnityEngine_UI_Image_Binding.Register(app);
            UnityEngine_UI_Graphic_Binding.Register(app);
            System_Collections_Generic_IEnumerable_1_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_IEnumerator_1_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Int32_Dictionary_2_String_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_String_MemberInfo_Binding_ValueCollection_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_String_MemberInfo_Binding_ValueCollection_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_List_1_String_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Int32_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_List_1_Int32_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Int32_List_1_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_List_1_Enum_Binding.Register(app);
            System_Collections_Generic_List_1_Enum_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Int32_ILTypeInstance_Binding_ValueCollection_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Int32_ILTypeInstance_Binding_ValueCollection_Binding_Enumerator_Binding.Register(app);
            System_Collections_ICollection_Binding.Register(app);
            UnityEngine_Mathf_Binding.Register(app);
            System_Collections_IList_Binding.Register(app);
            UnityEngine_Color_Binding.Register(app);
            System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Type_Object_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Int32_ILTypeInstance_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_KeyValuePair_2_Int32_ILTypeInstance_Binding.Register(app);
            BDFramework_Core_Debugger_Debugger_NetworkServer_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_String_List_1_Object_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Type_List_1_ILTypeInstance_Binding.Register(app);
            BDFramework_UnitTest_UnitTestBaseAttribute_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Type_List_1_ILTypeInstance_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_KeyValuePair_2_Type_List_1_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Int32_MethodInfo_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_String_Single_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_String_List_1_Action_1_Single_Binding.Register(app);
            System_Collections_Generic_List_1_Action_1_Single_Binding.Register(app);
            System_Action_1_Single_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_String_List_1_Single_Binding.Register(app);
            System_Collections_Generic_List_1_Single_Binding.Register(app);
            System_Collections_Generic_List_1_Single_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_String_String_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_String_List_1_Action_1_String_Binding.Register(app);
            System_Collections_Generic_List_1_Action_1_String_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_String_List_1_String_Binding.Register(app);
            System_Collections_Generic_List_1_Action_1_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_List_1_Action_1_ILTypeInstance_Binding_Enumerator_Binding.Register(app);
            System_Action_1_ILTypeInstance_Binding.Register(app);

            ILRuntime.CLR.TypeSystem.CLRType __clrType = null;
            __clrType = (ILRuntime.CLR.TypeSystem.CLRType)app.GetType (typeof(UnityEngine.Vector2));
            s_UnityEngine_Vector2_Binding_Binder = __clrType.ValueTypeBinder as ILRuntime.Runtime.Enviorment.ValueTypeBinder<UnityEngine.Vector2>;
            __clrType = (ILRuntime.CLR.TypeSystem.CLRType)app.GetType (typeof(UnityEngine.Vector3));
            s_UnityEngine_Vector3_Binding_Binder = __clrType.ValueTypeBinder as ILRuntime.Runtime.Enviorment.ValueTypeBinder<UnityEngine.Vector3>;
            __clrType = (ILRuntime.CLR.TypeSystem.CLRType)app.GetType (typeof(UnityEngine.Vector4));
            s_UnityEngine_Vector4_Binding_Binder = __clrType.ValueTypeBinder as ILRuntime.Runtime.Enviorment.ValueTypeBinder<UnityEngine.Vector4>;
            __clrType = (ILRuntime.CLR.TypeSystem.CLRType)app.GetType (typeof(UnityEngine.Quaternion));
            s_UnityEngine_Quaternion_Binding_Binder = __clrType.ValueTypeBinder as ILRuntime.Runtime.Enviorment.ValueTypeBinder<UnityEngine.Quaternion>;
        }

        /// <summary>
        /// Release the CLR binding, please invoke this BEFORE ILRuntime Appdomain destroy
        /// </summary>
        public static void Shutdown(ILRuntime.Runtime.Enviorment.AppDomain app)
        {
            s_UnityEngine_Vector2_Binding_Binder = null;
            s_UnityEngine_Vector3_Binding_Binder = null;
            s_UnityEngine_Vector4_Binding_Binder = null;
            s_UnityEngine_Quaternion_Binding_Binder = null;
        }
    }
}
